version: "3"

services:
    stratio-mongo:
        container_name: stratio-mongo
        image: mongo:3.4
        restart: always
        networks:
            - fleet
        logging:
            options:
                max-size: 1m

    stratio-orion:
        container_name: stratio-orion
        image: registry.lab.fiware.org/ids-orion
        command: -dbhost stratio-mongo -logLevel ERROR
        restart: always
        ports:
            - "11029:1026"
        depends_on:
            - stratio-mongo
        networks:
            - fleet
            - ids
        logging:
            options:
                max-size: 1m

    stratio-pep:
        container_name: stratio-pep
        image: registry.lab.fiware.org/pep-proxy
        restart: always
        volumes:
            - /opt/static/pep-stratio.js:/opt/fiware-pep-proxy/config.js
        depends_on:
            - stratio-orion
        networks:
            - fleet
            - ids
        logging:
            options:
                max-size: 1m

networks:
    fleet:
        external: true
    ids:
        external: true
